# Generated by Django 6.0.1 on 2026-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=30)),
                ('exchange_rate', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
